### ISSUE TITLE
Add a check to make sure the submitted file is an image.

### ISSUE THREAD

**Issue by SebastianKane** [Gavin1937/Your-Moon-CSULA#14]
Currently any file can be uploaded, this can be fixed with a simple check.

**Comment by Gavin1937** [comment]
we should limit the type image files that we accept, maybe only accept png, jpg, & bmp. Not sure about whether we should take raw camera file or not (like [.crw file](https://exiftool.org/canon_raw.html)), since they are super big.

just checking file headers should be good
