### ISSUE TITLE
Reading camera info from image exif

### ISSUE THREAD

**Issue by Gavin1937** [Gavin1937/Your-Moon-CSULA#15]
Images taken by camera usually contains exif info like camera model, exposure, iso, etc.
We should read them and display to the frontend.
This also means we need to add a set of input boxes to ask user for their equipment (camera & telescope)

**Comment by SebastianKane** [comment]
I have a way to get the exif data and I scraped the [exiftools website](file:///home/piranesi/Documents/ExifTool-tested%20Camera%20Models.html) and turned it into a json {make1:[model1,model2,model3...],...}. 

I was hoping to use the json for an autocomplete for both make and model using a component from a package like primevue or vuetify. That way we can both make it easier on the user and validate their input. However, I'm having issues getting that to work. I'm going to spend some time early next week trying to implement a component myself using some articles I found.
