### ISSUE TITLE
Site layout should be responsive.

### ISSUE THREAD

**Issue by SebastianKane** [Gavin1937/Your-Moon-CSULA#25]
![Image](https://github.com/Gavin1937/Your-Moon-CSULA/assets/98116733/c11eda0d-5436-4842-9805-03e1f28f147f)

This is how the site will likely look on a mobile phone. Ideally the css and html for uploadPage.vue should respond to the users screen size. This might be hard to implement unless vue has a feature to implement this.

**Comment by zaldivarjoan** [comment]
![Image](https://github.com/Gavin1937/Your-Moon-CSULA/assets/78455114/8121be16-8bb5-45f2-b394-6079aab5f8cf)

**Comment by zaldivarjoan** [comment]
![Image](https://github.com/Gavin1937/Your-Moon-CSULA/assets/78455114/dbd43f8c-de14-486b-8222-a01d13bca232)

The page doesn't bleed on the sides like it did before, either.

**Comment by johansen16** [comment]
You fixed it? So mobile is responsive?

Damn, i’m glad but that was supposed to be me n isabel’s task😬 but alright

**Comment by zaldivarjoan** [comment]
Sebastian asked me to work on it, so I did. Sorry 😮

**Comment by Gavin1937** [comment]
Seems like you are not on the latest commit of `dev` branch, you should sync your fork before you go too far

**Comment by zaldivarjoan** [comment]
yeah that's what I was gonna do right now thank you ❤

**Comment by SebastianKane** [comment]
> Sebastian asked me to work on it, so I did. Sorry 😮  

Yup sorry guys 😅 I was trying to think of something for Joan to do off the top of my head and this was the first thing that came to mind. I shoulda checked the board first.

There is plenty more that needs to be done and we need that landing page that Isabel is working on.

**Comment by johansen16** [comment]
It's alright, good job

Is it working for Ipad screen sizes as well? Any issues with the mobile
version as of now?

**Comment by zaldivarjoan** [comment]
Yeah tested it on all devices and so far, they are all functional and not funky-looking.

**Comment by Gavin1937** [comment]
addressed by https://github.com/Gavin1937/Your-Moon-CSULA/commit/d1bdecea29f8a60d3a2a6325ac871654d4b66585
