### ISSUE TITLE
Implement moon-selection logic in the frontend

### ISSUE THREAD

**Issue by Gavin1937** [Gavin1937/Your-Moon-CSULA#29]
In the uploadImage page, after user submit a photo, we will send it to the backend and run moon-detection algorithm on it. Frontend will receive the coordinate of the moon from the algorithm. We need to:
* automatically set the cropping box to the coordinate returned by the algorithm
* ask user: "Is this the moon?" (verifying moon-detection result)
* if user say yes
  * go to next page (addressed by #28)
* if user say no
  * allow user to move & resize the cropping box to the correct location
  * resize MUST with aspect ratio, the cropping box MUST be square

**Comment by SebastianKane** [comment]
As discussed in the last meeting this functionality will be replaced by the instructions pop-up and will no longer be necessary.
