### ISSUE TITLE
We need to have a central place for displaying error message to user

### ISSUE THREAD

**Issue by Gavin1937** [Gavin1937/Your-Moon-CSULA#43]
![image](https://github.com/Gavin1937/Your-Moon-CSULA/assets/71205842/9d78250e-b6af-4be8-8793-f13bf46c38fe)

Our original error prompt is in the bottom right side, and the one in the middle is added for prompting for invalid file type and size.
We need a central place for displaying error message, and we need to control its position and show/hide status

**Comment by Gavin1937** [comment]
is this issue done? If so, please send me a pr and we change its status from `Todo` to `In Progress`

**Comment by johansen16** [comment]
Not done, but i can work on it

**Comment by zaldivarjoan** [comment]
![Image](https://github.com/Gavin1937/Your-Moon-CSULA/assets/78455114/f1388c38-d796-4931-90a0-e7e46e2b0e1a)



Is this not what you were talking about?

**Comment by johansen16** [comment]
wait what do you mean?

**Comment by Gavin1937** [comment]
> 
> ![Image](https://github.com/Gavin1937/Your-Moon-CSULA/assets/78455114/f1388c38-d796-4931-90a0-e7e46e2b0e1a)
> 
> 
> 
> Is this not what you were talking about @Gavin1937 ? This was already pushed into the main.

This is really close, but we don't want that duplicate "network error".

And please make sure that this error prompt is responsive to different display ratios (mobile, desktop, etc)
